db/migrate/20181212092200_add_img_updated_at_to_images.rb
lib/apress/images/version.rb
lib/tasks/images_table.rake

https://jira.railsc.ru/browse/BPC-13545

 fix: add img_updated_at and fill them

---

Gemfile
app/models/apress/images/image.rb
db/migrate/20181212092200_add_img_updated_at_to_images.rb
lib/apress/images/version.rb
lib/tasks/images_table.rake
spec/app/interactors/apress/images/delete_images_spec.rb
spec/app/models/apress/images/extensions/background_processing_spec.rb
spec/internal/db/schema.rb

https://jira.railsc.ru/browse/BPC-13545

 fix: rename updated_at to img_updated_at

---

app/models/apress/images/extensions/image.rb
spec/app/models/apress/images/extensions/image_spec.rb

https://jira.railsc.ru/browse/GOODS-1571

fix: clear file if image creation failed

---

Gemfile
README.md
app/interactors/apress/images/delete_images.rb
app/models/apress/images/extensions/background_processing.rb
app/models/apress/images/extensions/image.rb
app/models/concerns/apress/images/deduplicable.rb
app/models/concerns/apress/images/imageable.rb
db/migrate/20190206100943_update_duplicate_img_function.rb
db/schema/public/image_update_img_from_parent.sql
lib/apress/images/engine.rb
lib/apress/images/extensions/attachment.rb
lib/apress/images/extensions/attachment/deduplicable.rb
lib/apress/images/extensions/interpolations/deduplicable.rb
lib/tasks/images_deduplication.rake
spec/app/models/concerns/apress/images/deduplicable_spec.rb
spec/internal/db/schema.rb

feature: add deduplication

---

Appraisals
app/models/concerns/apress/images/deduplicable.rb
apress-images.gemspec
spec/app/models/concerns/apress/images/deduplicable_spec.rb

fix: take fingerprint parent when duplicate from

---

app/models/concerns/apress/images/dangling_cleanable.rb
app/models/concerns/apress/images/deduplicable.rb
spec/app/models/concerns/apress/images/deduplicable_spec.rb

fix: enqueue clean dangling original image after destroy

---

lib/tasks/images_deduplication.rake

fix: do not delete file when processed

---

Gemfile
lib/tasks/images_deduplication.rake

fix: retry when webdav error in deduplication task

---

lib/apress/images/extensions/io_adapters/uri_adapter.rb
lib/apress/images/version.rb

https://jira.railsc.ru/browse/BPC-14977

 fix: do not verify ssl

---

app/models/concerns/apress/images/imageable.rb
lib/apress/images/engine.rb
lib/apress/images/version.rb

https://jira.railsc.ru/browse/BPC-15117

feature: configure default image styles

---

app/models/concerns/apress/images/deduplicable.rb

https://jira.railsc.ru/browse/GOODS-2013

fix: always use index when find original

---

app/models/concerns/apress/images/imageable.rb
lib/apress/images/version.rb

https://jira.railsc.ru/browse/BPC-15426

fix: remove default options for original style

---

Gemfile
lib/tasks/images_deduplication.rake

https://jira.railsc.ru/browse/GOODS-1893

fix: retry on load file when fill img fingerprint

---

.drone.yml
app/models/apress/images/extensions/image.rb
spec/app/models/apress/images/extensions/image_spec.rb
spec/app/models/apress/images/imageable_spec.rb
spec/app/models/concerns/apress/images/deduplicable_spec.rb
spec/factories/images.rb
spec/internal/app/models/default_duplicated_image.rb
spec/internal/app/models/simple_duplicated_image.rb
spec/spec_helper.rb

https://jira.railsc.ru/browse/GOODS-1799

feat: add corrupted_image_file_validation

---

app/models/apress/images/extensions/image.rb
spec/app/models/apress/images/extensions/background_processing_spec.rb
spec/app/models/apress/images/imageable_spec.rb

https://jira.railsc.ru/browse/GOODS-1799

fix: validate image file only on create

---

app/models/apress/images/extensions/image.rb
lib/apress/images/extensions/attachment.rb
spec/app/models/apress/images/imageable_spec.rb
spec/lib/apress/images/extensions/attachment_spec.rb

https://jira.railsc.ru/browse/GOODS-2008

feat: remove search of biggest style

---

app/assets/javascripts/images.js
app/assets/javascripts/templates/images/croping_popup.hamlbars
app/helpers/apress/images/form_tag_helper.rb
app/views/apress/images/_config.html.haml

[MINOR] Доавлен параметр popup_title, для изменения заголовка попапа кропа (прежний заголовок остался значением по умолчанию). Добавлено событие начала загрузки (после нажатия кнопки "сохранить").
https://jira.railsc.ru/browse/BPC-16125

feature: add custom title to crop popup, add imageStartUploading event

---

app/assets/javascripts/images.js
app/assets/javascripts/templates/images/croping_popup.hamlbars
app/assets/stylesheets/images/croping_popup.scss

[PATCH]: Установит минимальную ширину (460px) и высоту (380px) попапа для нарезки изображений.
https://jira.railsc.ru/browse/BPC-16125

fix: add min crop popup width/height

---

Gemfile
app/models/apress/images/extensions/image.rb
config/locales/ru.yml
spec/app/models/apress/images/extensions/image_spec.rb

https://jira.railsc.ru/browse/GOODS-2265

fix: не будем показывать на проде ошибку imagemagick

---

Gemfile
db/migrate/20200507161547_recreate_duplicate_img_function.rb
db/schema/public/image_update_img_from_parent.sql
lib/tasks/images_deduplication.rake

https://jira.railsc.ru/browse/GOODS-2367

fix: attempt to fix processing flag for duplicates

---

app/assets/javascripts/images.js

https://jira.railsc.ru/browse/BPC-16749

fix initWidth and initHeight in _initCropArea function

---

app/jobs/apress/images/update_duplicate_image_job.rb
spec/app/jobs/apress/images/update_duplicate_image_job_spec.rb

https://jira.railsc.ru/browse/GOODS-2524

fix: define perform method for delayed job

---

app/models/concerns/apress/images/deduplicable.rb
lib/apress/images/version.rb

https://jira.railsc.ru/browse/BPC-17557

fix: check on enqueue_dangling_image method exists

---

Gemfile
app/controllers/apress/images/images_controller.rb

https://jira.railsc.ru/browse/PC4-26810

fix: previews for images without background processing

---

app/assets/stylesheets/images/croping_popup.scss

https://jira.railsc.ru/browse/BPC-19097

fix: fix image size in croping popup

---

app/models/apress/images/extensions/background_processing.rb
app/models/concerns/apress/images/imageable.rb
app/models/concerns/apress/images/online_processable.rb
lib/apress/images/version.rb

https://jira.railsc.ru/browse/BPC-19985

fix: extract online_processing attr to model

---

app/models/concerns/apress/images/deduplicable.rb
docker-compose.yml

https://jira.railsc.ru/browse/BPC-20526

feature: return true when images destroy

---

app/models/concerns/apress/images/deduplicable.rb
docker-compose.yml
lib/apress/images/version.rb

return true when images destroy
you do not need to do anything to connect to the project

MERGE: bz2022-may-1 into master and Release 7.7.0

---

app/models/concerns/apress/images/imageable.rb

https://jira.railsc.ru/browse/SG-8243

feature(imageable): add webp format

---

Gemfile
README.md
app/interactors/apress/images/delete_images.rb
app/models/apress/images/extensions/background_processing.rb
app/models/apress/images/extensions/image.rb
app/models/concerns/apress/images/deduplicable.rb
app/models/concerns/apress/images/imageable.rb
db/migrate/20190206100943_update_duplicate_img_function.rb
db/schema/public/image_update_img_from_parent.sql
lib/apress/images/engine.rb
lib/apress/images/extensions/attachment.rb
lib/apress/images/extensions/attachment/deduplicable.rb
lib/apress/images/extensions/interpolations/deduplicable.rb
lib/tasks/images_deduplication.rake
spec/app/models/concerns/apress/images/deduplicable_spec.rb
spec/internal/db/schema.rb

https://jira.railsc.ru/browse/SG-8345

feature(deduplication): add deduplication of images

---

.drone.yml
Gemfile.lock
gemfiles/rails4.2.gemfile.lock
lib/apress/images/version.rb

делать ничего не надо, просто попытка выпустить таки версию гема

fix: do not rm lock files in drone

---

app/assets/javascripts/images.js

https://jira.railsc.ru/browse/PC4-30113
Нужна будет ветка март-1, наверное от мастера

fix: добавит проверку размера и расширения перед загрузкой картинки

---

db/migrate/20240301082737_add_type_to_images.rb

https://jira.railsc.ru/browse/SG-8601

feature(images): add type column to images

---

app/assets/javascripts/images.js
lib/apress/images/version.rb

При подключении ничего делать не надо

MERGE: master...pc-march-1 and Release v7.8.3

---

app/models/concerns/apress/images/position_normalizable.rb

https://jira.railsc.ru/browse/SG-8649

feature(position_normalizable): add type in PARTITION BY clause in normalize_positions

---

lib/apress/images/extensions/interpolations/deduplicable.rb

https://jira.railsc.ru/browse/GOODS-4093

fix: id_partition when ID more then billion

---

lib/apress/images/extensions/interpolations/deduplicable.rb
lib/apress/images/version.rb

[#33178](https://github.com/abak-press/blizko/pull/33178)
@GeVhoo

Merge goods2024-hotfix into master and Release 7.8.4

---

app/assets/javascripts/images.js

https://jira.railsc.ru/browse/BPC-23502

fix: do not try to crop svg images
